export const popularCities = [
  'Tokyo, Japan',
  'Paris, France',
  'New York, USA',
  'London, UK',
  'Barcelona, Spain',
  'Dubai, UAE',
  'Rome, Italy',
  'Singapore',
  'Sydney, Australia',
  'Bali, Indonesia',
  'Istanbul, Turkey',
  'Bangkok, Thailand',
  'Seoul, South Korea',
  'Amsterdam, Netherlands',
  'Santorini, Greece',
  'Prague, Czech Republic',
  'Vienna, Austria',
  'Copenhagen, Denmark',
  'Toronto, Canada',
  'Stockholm, Sweden',
  'Lisbon, Portugal',
  'Berlin, Germany',
  'Venice, Italy',
  'Maldives',
  'Kyoto, Japan',
  'Hong Kong',
  'Los Angeles, USA',
  'Edinburgh, Scotland',
  'Cape Town, South Africa',
  'Reykjavik, Iceland',
];
